# Load secure environment variables for access by other scripts
language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
dist: trusty
sudo: required
addons:
  # For testing with Selenium
  chrome: stable
before_install:
  - # start chrome and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  # Set Uploadpie auth key in behat config file via env var
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql
    php5-intl
  - sudo sed -i -e "s,/var/www/html,$(pwd)/public_html,g" /etc/apache2/sites-available/000-default.conf
  - sudo sed -i -e "/DocumentRoot/i\ServerName phplist.dev" /etc/apache2/sites-available/000-default.conf
  - sudo sed -i -e "/DocumentRoot/i\DirectoryIndex index.php index.html" /etc/apache2/sites-available/000-default.conf
  - sudo sed -i -e "s,/var/www,$(pwd)/public_html,g" /etc/apache2/apache2.conf
  - echo "127.0.0.1 phplist.dev" | sudo tee -a /etc/hosts
  - sudo chmod o+rx /home/travis
  - sudo /etc/init.d/apache2 restart
  - sudo cp -f tests/travis-ci/behat.yml behat.yml
  - sudo cp -f tests/travis-ci/config.php public_html/lists/config/config.php
  - mkdir /home/travis/build/xh3n1/phplist3/logs/ 
  - composer self-update
  - composer install --prefer-dist
  - cd vendor/bin && ln -s ../njoannidi/php-lint-bash/phpLint && cd ../../
  - ls -l vendor/bin
  - cd public_html/lists/admin/ui/ && wget https://github.com/phpList/phplist-ui-bootlist/archive/master.tar.gz
    && tar -xzf master.tar.gz && mv phplist-ui-bootlist-master phplist-ui-bootlist &&
    rm master.tar.gz && cd ../../../../
  - mysql -e 'SET GLOBAL wait_timeout = 5400;'
  - mysql -e 'create database phplistdb;'
  # Start xvfb (for use with Selenium)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - curl -v http://localhost/index.html
  - curl -v http://phplist.dev/index.html
  - curl -v http://127.0.0.1/index.html
  - curl -v http://localhost/lists/
  - curl -v http://phplist.dev/lists/
  - curl -v http://127.0.0.1/lists/
script:
  - vendor/bin/phpLint ./public_html
  - vendor/bin/behat
  - vendor/bin/upload-textfiles "logs/*.log"
after_failure:
  - echo "Failures detected. Outputing additional logs:"
  - sudo ls -l /etc/apache2/sites-available/
  - sudo cat /etc/apache2/apache2.conf
  - sudo cat /etc/apache2/sites-available/000-default.conf
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/mysql/error.log
